port: 8083

server:
  port: ${port}

management:
  server:
    port: ${port}

  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

spring:
  application:
    name: notification-service
  data:
    mongodb:
      # Nome do Service + Namespace (DNS interno do K8s)
      host: ${MONGO_HOST:mongodb-service.production}
      port: 27017
      database: kubernetes
      authentication-database: admin
      auto-index-creation: true
      # Injeta via variáveis de ambiente (Segurança)
      username: ${MONGO_USERNAME:root}
      password: ${MONGO_PASSWORD}
